### ISSUE TITLE
visual demonstration content for Keith@DARPA speech

### ISSUE THREAD

**Issue by mattlebeau-galois** [GaloisInc/BESSPIN-Voter-Registration#39]
AC:
Generate visual demo for:
- this is how it is protected with SSITH hardware
- visual demonstration of the hack / protection

June 12th keith needs a draft (storyboard) of demo to submit for DARPA review
July 10th needs to be final-final and approved for DISTAR

**Comment by kiniry** [comment]
This was completed ages ago, so I'm closing this issue.
